on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  pull_request_review_comment:
    types: [created]

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: printenv
    - run: cat $GITHUB_EVENT_PATH
